I'm sorry, but an uncaught exception occurred.

Compiling ATL code at game/venaprologue.rpy:192
  File "game/venaprologue.rpy", line 194, in script
    k "“Vena ben… Galiba bundan sorumlu olan kişiyi gördüm.”"
  File "renpy/common/00library.rpy", line 268, in say
    who(what, interact=interact, *args, **kwargs)
NameError: name 'zoom' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/venaprologue.rpy", line 194, in script
    k "“Vena ben… Galiba bundan sorumlu olan kişiyi gördüm.”"
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/ast.py", line 716, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/exports.py", line 1415, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "renpy/common/00library.rpy", line 268, in say
    who(what, interact=interact, *args, **kwargs)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/character.py", line 1223, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/character.py", line 875, in do_display
    **display_args)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/character.py", line 621, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/display/core.py", line 3276, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/display/core.py", line 3694, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/display/core.py", line 558, in visit_all
    for d in self.visit():
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/atl.py", line 603, in visit
    block = self.compile()
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/atl.py", line 510, in compile
    block = self.atl.compile(self.context)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/atl.py", line 705, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/atl.py", line 953, in compile
    value = ctx.eval(expr)
  File "C:\Users\beste\OneDrive\Belgeler\renpy-7.4.8-sdk/renpy/atl.py", line 260, in eval
    return eval(expr, renpy.store.__dict__, self.context) # @UndefinedVariable
  File "<string>", line 1, in <module>
NameError: name 'zoom' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
AVSC 1.0
Wed Aug 18 13:01:20 2021
