I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/haruprologue.rpy", line 23, in script
    define Waceera_Entry = EncEntry(
  File "game/haruprologue.rpy", line 23, in script
    define Waceera_Entry = EncEntry(
  File "game/haruprologue.rpy", line 24, in <module>
    parent=your_new_encyclopaedia,
NameError: name 'your_new_encyclopaedia' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 550, in main
    renpy.game.context().run(node)
  File "game/haruprologue.rpy", line 23, in script
    define Waceera_Entry = EncEntry(
  File "game/haruprologue.rpy", line 23, in script
    define Waceera_Entry = EncEntry(
  File "renpy/ast.py", line 2213, in execute
    self.set()
  File "renpy/ast.py", line 2224, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/haruprologue.rpy", line 24, in <module>
    parent=your_new_encyclopaedia,
NameError: name 'your_new_encyclopaedia' is not defined

Windows-10-10.0.22000
Ren'Py 7.4.10.2178
The Calling 1.0
Sat Nov 27 16:18:52 2021
