I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/venaprologue.rpy", line 25, in script
    play music thecalling3
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/venaprologue.rpy", line 25, in <module>
    play music thecalling3
NameError: name 'thecalling3' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/venaprologue.rpy", line 25, in script
    play music thecalling3
  File "renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/venaprologue.rpy", line 25, in <module>
    play music thecalling3
NameError: name 'thecalling3' is not defined

Windows-10-10.0.22000
Ren'Py 7.4.10.2178
The Calling 1.0
Tue Sep 13 19:59:25 2022
